Add forklifts, barriers and cages
RobotecAI/robotec-warehouse-assets pull request #2
Opened 2024-08-01 09:49 UTC by c00kiepreferences

## Pull Request details
Added two Gems with assets:
- `RobotecWarehouseBarriersAndCagesAssets`: Gem with warehouse barriers and cage walls assets.
- `RobotecWarehouseForkliftsAssets`: Gem with warehouse forklifts assets.

## Checklist
- [x] I updated the `README.md` document to add information about new Gem(s).
- [x ] I added git attributes file.
- [x] I filled in the `gem.json` file with the necessary information, including license, origin, and summary in the new Gem(s).
- [x] I checked if the folder structure and filenames follow the convention described in `README.md`.
- [x] I added the `NOTICE` file with some additional comments on the license. 
- [x] I checked if the origins of prefabs follow the convention.

2024-08-05 09:56 UTC, jhanca-robotecai requested changes
I am okay with the names and the structure, it follows the proposed scheme. The only problem I see is that LFS is not properly initialized. The PRs need to be reordered.

2024-08-05 14:26 UTC, jhanca-robotecai approved these changes
I fixed the LFS and force-pushed the code. It is okay for me know.

2024-08-08 11:06 UTC, pawelbudziszewski requested changes
Forklifts should be rotated to have X-axis forward.

2024-08-08 11:06 UTC, pawelbudziszewski commented on RobotecWarehouseBarriersAndCagesAssets/Assets/Cages/Models/Materials/Textures/Cage-BaseColor.png
Names of these files should be separated by an underscore, not a dash

2024-08-09 11:45 UTC, c00kiepreferences commented on RobotecWarehouseBarriersAndCagesAssets/Assets/Cages/Models/Materials/Textures/Cage-BaseColor.png
I tried to change that, but for some reason, as soon as I changed the dash to the underscore, textures became broken. Other names i tried did not show this kind of issue (i also checked with asset processor, it wasn't a case of it still processing textures).

2024-08-16 11:05 UTC, jhanca-robotecai commented on RobotecWarehouseBarriersAndCagesAssets/Assets/Cages/Models/Materials/Textures/Cage-BaseColor.png
PNG files with `_BaseColor` suffix are automatically loaded as `Albedo`. I added `assetinfo` files to overwrite this issue.

2024-08-16 16:00 UTC, pawelbudziszewski approved these changes

2024-08-19 08:58 UTC, merged